In [1]:
%run ../IterativeRF.py

In [2]:
import pandas as pd
pd.Series.mode?

Signature: pd.Series.mode(self, dropna: 'bool' = True) -> 'Series'
Docstring:
Return the mode(s) of the Series.

The mode is the value that appears most often. There can be multiple modes.

Always returns Series even if only one value is returned.

Parameters
----------
dropna : bool, default True
    Don't consider counts of NaN/NaT.

Returns
-------
Series
    Modes of the Series in sorted order.
File:      ~/miniconda3/envs/dat/lib/python3.11/site-packages/pandas/core/series.py
Type:      function

In [12]:
pd.Series(['a',None,'b','c', 'b']).mode()[0]

'b'

In [2]:
X = np.array([[1, 2, 3],
                  [4, np.nan, 6],
                  [7, 8, 9],
                  [np.nan, 11, 6],
                  [13, 14, np.nan]])
X

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.],
       [nan, 11.,  6.],
       [13., 14., nan]])

In [3]:
medians = np.array([np.median(np.array([1,4,7,13])), np.median([2,8,11,14]), np.median(np.array([3,6,9,6]))])
medians

array([5.5, 9.5, 6. ])

In [4]:
irf = IterativeRF()

In [8]:
irf._median_impute(X=X)

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  9.5,  6. ],
       [ 7. ,  8. ,  9. ],
       [ 5.5, 11. ,  6. ],
       [13. , 14. ,  6. ]])